name: Refresh Leaderboard

on:
  push:
    branches:
      - main 
      
env:
  DBKEY: ${{ secrets.DBKEY }}
  DBTOKEN: ${{ secrets.DBTOKEN }}

jobs:
  update-leaderboard:
    runs-on: ubuntu-latest

    steps:
    - name: Download repository
      uses: actions/checkout@v3
      with:
        repository: pstlo/pstlo.github.io
        ref: main

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-dotenv
        pip install dnspython
        pip install certifi
        pip install cryptography
        python -m pip install pymongo==3.11

    - name: Run script and commit changes
      run: |        
        python navigator/GetLeaderboard.py  
        git add navigator/Leaders.json
        git commit -m "Refresh Leaders.json"
        git push
